### ISSUE TITLE
Review Assignments, Upload to Personal Portfolio

### ISSUE THREAD

**Issue by castower** [learn-code-codecamp/python#36]
Upload assignments to personal portfolio and review any last-minute coding challenges

**Comment by sunaynagoel** [comment]
Do you wan to pick a particular project so we can both work on same one. 
suggestion: 
1. monty carlo simulation
2. Rock paper scissors

**Comment by castower** [comment]
completed rock, paper, scissors: https://github.com/castower/python-projects/blob/master/rock-paper-scissors-cs.py

**Comment by sunaynagoel** [comment]
Complete and uploaded 
https://github.com/sunaynagoel/python-projects/blob/master/RockPaper.py
